import {
  Home,
  Box,
  Mail,
  ShoppingCart,
  Megaphone,
  Building2,
  Truck,
  FileSearch,
  HelpCircle,
  ShoppingBag,
  CircleUser,
  ArrowLeftRight,
  Handshake,
  MessageSquareText,
  LayoutDashboard,
  Users,
  CreditCard,
  Globe,
} from "lucide-react";

export const roleBasedMenuItems = {
  seller: [
    {
      name: "Home",
      icon: Home,
      path: "/seller/dashboard",
      relatedPaths: ["/seller/dashboard", "/seller/dashboard/todo"],
    },
    {
      name: "Store",
      icon: ShoppingBag,
      path: "/seller/store",
      relatedPaths: ["/seller/store"],
    },
    {
      name: "Products",
      icon: Box,
      path: "/seller/products",
      relatedPaths: ["/seller/products"],
    },
    {
      name: "Communications",
      icon: Mail,
      path: "/seller/message",
      relatedPaths: ["/seller/message"],
    },
    {
      name: "Orders",
      icon: ShoppingCart,
      path: "/seller/orders",
      relatedPaths: ["/seller/orders"],
    },
    {
      name: "Campaigns",
      icon: Megaphone,
      path: "/seller/campaigns",
      relatedPaths: ["/seller/campaigns"],
    },
    {
      name: "Company & Site",
      icon: Building2,
      path: "/seller/company&site",
      relatedPaths: ["/seller/company&site"],
    },
    {
      name: "Logistics",
      icon: Truck,
      path: "/seller/logistics",
      relatedPaths: ["/seller/logistics"],
    },
    {
      name: "Customs Clearance",
      icon: FileSearch,
      path: "/seller/customs",
      relatedPaths: ["/seller/customs"],
    },
    {
      name: "Help Center",
      icon: HelpCircle,
      path: "/seller/help",
      relatedPaths: ["/seller/help"],
    },
  ],
  buyer: [
    {
      name: "Dashboard",
      icon: LayoutDashboard,
      path: "/buyer/dashboard",
      relatedPaths: ["/buyer/dashboard", "/buyer/dashboard/todo"],
    },
    {
      name: "Message",
      icon: MessageSquareText,
      path: "/buyer/message",
      relatedPaths: ["/buyer/message"],
    },
    {
      name: "My Orders",
      icon: ShoppingCart,
      path: "/buyer/my-orders",
      relatedPaths: ["/buyer/my-orders"],
    },
    {
      name: "Buying Leads",
      icon: Handshake,
      path: "/buyer/buying-leads",
      relatedPaths: ["/buyer/buying-leads"],
    },
    {
      name: "Transactions",
      icon: ArrowLeftRight,
      path: "/buyer/transactions",
      relatedPaths: ["/buyer/transactions"],
    },
    {
      name: "Profile",
      icon: CircleUser,
      path: "/buyer/update-profile",
      relatedPaths: ["/buyer/update-profile"],
    },
  ],
  admin: [
    {
      name: "Dashboard",
      icon: LayoutDashboard,
      path: "/admin/dashboard",
      relatedPaths: ["/admin/dashboard"],
    },

    {
      name: "Manage Leads",
      icon: Box,
      path: "/admin/manage-leads",
      relatedPaths: ["/admin/manage-leads"],
    },
    {
      name: "Manage Catalog",
      icon: Box,
      path: "/admin/manage-catalog",
      relatedPaths: ["/admin/manage-catalog"],
    },
    {
      name: "Manage Products",
      icon: Box,
      path: "/admin/manage-products",
      relatedPaths: ["/admin/manage-products"],
    },
    {
      name: "Manage Orders",
      icon: ShoppingCart,
      path: "/admin/manage-orders",
      relatedPaths: ["/admin/manage-orders"],
    },
    {
      name: "Manage Businesses",
      icon: Box,
      path: "/admin/manage-businesses",
      relatedPaths: ["/admin/manage-businesses"],
    },
    {
      name: "Advertisement",
      icon: Box,
      path: "/admin/manage-advertisement",
      relatedPaths: ["/admin/manage-advertisement"],
    },
    {
      name: "E-commerce",
      icon: Box,
      path: "/admin/e-commerce",
      relatedPaths: ["/admin/e-commerce"],
    },
    {
      name: "Users",
      icon: CircleUser,
      path: "/admin/users",
      relatedPaths: ["/admin/users"],
    },
    {
      name: "Logistics",
      icon: Truck,
      path: "/admin/logistics",
      relatedPaths: ["/admin/logistics"],
    },
    {
      name: "Subscribers",
      icon: Users,
      path: "/admin/subscribers",
      relatedPaths: ["/admin/subscribers"],
    },
    {
      name: "Our Staff",
      icon: Users,
      path: "/admin/our-staff",
      relatedPaths: ["/admin/our-staff"],
    },
    {
      name: "Admin List",
      icon: Users,
      path: "/admin/admin-list",
      relatedPaths: ["/admin/admin-list"],
    },
    {
      name: "Manage Subscriptions",
      icon: CreditCard,
      path: "/admin/manage-subscriptions",
      relatedPaths: ["/admin/manage-subscriptions"],
    },
    {
      name: "Manage Website",
      icon: Globe,
      path: "/admin/manage-website",
      relatedPaths: ["/admin/manage-website"],
    },
    {
      name: "Settings",
      icon: FileSearch,
      path: "/admin/settings",
      relatedPaths: ["/admin/settings"],
    },
  ],
};
